### ISSUE TITLE
Only show CSTC tranformation tab if filter is activated

### ISSUE THREAD

**Issue by mschader** [usdAG/cstc#13]
I think it is kinda confusing to show the CSTC tab with its transformation even if the filter is not activated. It makes the impression, that the request is still being manipulated before sending. I would propose, that the CSTC tab only shows up if it is actually active.

E.g. If "Repeater" is not selected as filter in CSTC, the CSTC tab should not be shown at the Repeater.

**Comment by qtc-de** [comment]
To the best of our knowledge this is currently not possible. 

A little bit background: The CSTC tab is implemented as a [IMessageEditorTab](https://portswigger.net/burp/extender/api/burp/IMessageEditorTab.html). Each MessageEditor that gets created by Burp calls the ``createInstance`` method of an [IMessageEditorTabFactory](https://portswigger.net/burp/extender/api/burp/IMessageEditorTabFactory.html) to receive the tabs it should register. The problem is now, that ``createInstance`` gets no information about the context in which the tab will be embedded. 

So the only thing we can do is return our instances of ``IMessageEditorTab`` on calls to ``createInstance``, but since we do not know where the corresponding instances are being used, there is no possibility to enable/disable the tabs in specific areas of Burp.

If someone knows a good solution for that, we are happy to hear about. Otherwise we have to wait until Burp releases some new API features.
